# Generated by Django 4.1 on 2022-08-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('Gym Session', 'Gym Session'), ('Therapy Session', 'Therapy Session'), ('Massage', 'Massage'), ('Spa', 'Spa')], max_length=100)),
                ('date', models.CharField(help_text='Choose a date', max_length=50)),
                ('time', models.CharField(choices=[('8:00AM', '8:00AM'), ('9:00AM', '9:00 AM'), ('10:00AM', '10:00 AM'), ('11:00AM', '11:00 AM'), ('12:00PM', '12:00 PM'), ('1:00PM', '1:00 PM'), ('2:00PM', '2:00 PM'), ('3:00PM', '3:00 PM'), ('4:00PM', '4:00 PM'), ('5:00PM', '5:00 PM'), ('6:00PM', '6:00 PM'), ('7:00PM', '7:00 PM')], max_length=50)),
            ],
        ),
    ]
