# Generated by Django 4.1 on 2022-08-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='consultation',
            name='service',
            field=models.CharField(choices=[('Gym Session', 'Gym Session'), ('Therapy Session', 'Therapy Session'), ('Massage', 'Massage'), ('Spa', 'Spa'), ('Healthy Food', 'Healthy Food')], max_length=100),
        ),
    ]
