# Generated by Django 4.1 on 2022-08-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscription_alter_consultation_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='email',
            new_name='subscriber_email',
        ),
    ]
