# Generated by Django 4.1 on 2022-08-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('focus', models.CharField(choices=[('Chest', 'Chest'), ('Abs', 'Abs'), ('Arms', 'Arms'), ('Legs', 'Legs')], max_length=50)),
                ('main_goal', models.CharField(choices=[('Lose weight', 'Lose weight'), ('Build Muscles', 'Build Muscles'), ('Keep Fit', 'Keep Fit')], max_length=50)),
                ('motivation', models.CharField(choices=[('Feel Confident', 'Feel Confident'), ('Release Stress', 'Release Stress'), ('Improve Health', 'Improve Health'), ('Boost Energy', 'Boost Energy')], max_length=100)),
            ],
        ),
    ]
