# Generated by Django 4.1 on 2022-08-17 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_remove_question_question_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('focus', models.CharField(choices=[('Chest', 'Chest'), ('Abs', 'Abs'), ('Arms', 'Arms'), ('Legs', 'Legs')], max_length=50)),
                ('main_goal', models.CharField(choices=[('Lose weight', 'Lose weight'), ('Build Muscles', 'Build Muscles'), ('Keep Fit', 'Keep Fit')], max_length=50)),
                ('motivation', models.CharField(choices=[('Feel Confident', 'Feel Confident'), ('Release Stress', 'Release Stress'), ('Improve Health', 'Improve Health'), ('Boost Energy', 'Boost Energy')], max_length=100)),
                ('activity_level', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately Active'), ('Very Active', 'Very Active')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
