# Generated by Django 4.1 on 2022-08-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_coach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'coaches'},
        ),
        migrations.AddField(
            model_name='coach',
            name='image',
            field=models.ImageField(default='coach.jog', upload_to='coach_pictures'),
        ),
    ]
