# Generated by Django 4.1 on 2022-08-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_position', models.CharField(max_length=100)),
                ('image', models.ImageField(default='testimonies.jpg', upload_to='testimonials')),
                ('comment', models.TextField()),
            ],
        ),
    ]
