# Generated by Django 4.1 on 2022-08-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_testimonies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonies',
            options={'verbose_name_plural': 'Testimonies'},
        ),
    ]
