# Generated by Django 4.1 on 2022-08-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_testimonies_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Success_Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='success_stories_pictures')),
                ('job', models.CharField(max_length=100)),
            ],
        ),
    ]
