# Generated by Django 4.1 on 2022-08-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_success_stories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='success_stories',
            options={'verbose_name_plural': 'Success_Stories'},
        ),
        migrations.AddField(
            model_name='success_stories',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
