# Generated by Django 4.1 on 2022-08-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_success_stories_options_success_stories_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='Service'),
        ),
    ]
