# Generated by Django 4.1 on 2022-08-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post.jpg', upload_to='post_pictures'),
        ),
    ]
